#+TITLE: Software & Infrastructure Engineer
#+AUTHOR: Marcos Benevides
#+EMAIL: marcos.schonfinkel@gmail.com

#+LATEX_CLASS: moderncv
#+LATEX_HEADER: \usepackage[scale=0.95]{geometry}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[portuguese]{babel}
#+LATEX_HEADER: \firstname{Marcos}\lastname{Benevides}
#+OPTIONS: tags:nil toc:nil

#+GITHUB: schonfinkel
#+LINKEDIN: schonfinkel
#+HOMEPAGE: schonfinkel.github.io
#+LINKEDIN: schonfinkel
#+ADDRESS: São Luís - MA - Brazil
#+PHOTO: ./static/img/logo.png

#+CVSTYLE: banking
#+CVCOLOR: black

* Executive Summary
I have 6+ years of experience dealing with backend systems and infrastructure,
leveraging functional programming in both domains.

* Experience

** Software Development Engineer 2
:PROPERTIES:
:CV_ENV: cventry
:FROM:  <2022-01-04 Tue>
:EMPLOYER: Divisions Maintanence Group
:LOCATION: Ohio, United States (Remote)
:END:

- F# Backend development.
- Bugfixes and major improvements in a legacy monorepo, which included
  interfacing and properly debugging issues in a 10+ years old database.
- Design and bootstrap newer solutions so we can migrate away from old
  systems. By implementing immutable architectures based on functional
  programming ideas.
- I've also built a lot of custom tooling to enable my team to locally reproduce
  issues in our microservices architecture.

** F# Freelancer & Cloud Engineer
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2023-08-01 Tue>
:TO:       <2023-11-28 Tue>
:EMPLOYER: Kanagawa Inc.
:LOCATION: São Luís, Brazil (Remote)
:END:

- Worked alongside the technical founder and refactored existing F#
  applications.
- Instructed younger software developers who where unfamiliar with functional
  programming.
- Bootstrapped the cloud infrastructure in Terraform.
- Engineered all automation pipelines in github.

** Lead DevOps Engineer
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2022-02-28 seg>
:TO:       <2022-09-26 seg>
:EMPLOYER: datarisk.io
:LOCATION: Florianópolis, Brazil (Remote)
:END:

- Joined the company as engineer #3, starting as a Python Backend Engineer. Then
  got promoted all the way to lead our DevOps department.
- Led an effort to move cloud providers, inherited a poorly maintained, scarcely
  monitored and undocumented AWS infrastructure. In less than 2 years we had
  moved to Azure, with proper monitoring, cost-saving measures and a
  infra-as-code approach.
- Reduced our cloud-billing by 80%.
- Mentored my interns until they were able to safely replace me (and be promoted).
- F# + Python backend development.

* Skills

- Programming :: /Functional/ (Elixir, Erlang, Gleam, F#, Haskell, Nix), /Object Oriented/ (C#, Python)
- Devops :: /Infra/ (Linux, NixOS), /Tools/ (Git, Kafka, Kubernetes, Makefile, Terraform)
- Architecting :: Monolithic and Distributed Designs, Cloud (AWS, Azure), Automation
- DBA :: /Languages/ (SQL, Datalog, Prolog), RDBMS (PostgreSQL, SQL Server, SQLite)
- Management :: Technical Leadership
