:PROPERTIES:
:ID:       60f014f9-8a82-43b8-ae13-dee68b9470bf
:END:
#+title: Statements (PostgreSQL)
#+filetags: :postgresql: :sql:

- [[id:1949c98e-e1c0-474b-b383-c76aa418d583][PostgreSQL]]

* ~SELECT~
** ~LIKE~ and ~ILIKE~
** ~DISTINCT~
** ~LIMIT~ and ~OFFSET~

#+begin_quote
~LIMIT~ and ~OFFSET~ are used to return a portion of data from a resultset
generated by a query; the ~LIMIT~ clause is used to limit the number of records in
output and the ~OFFSET~ clause is used to provide PostgreSQL with the position in
the resultset from which to start returning data.

[cite:@ferrari2023postgres p.111]
#+end_quote

* Combining Queries

** ~UNION~ / ~UNION ALL~

#+begin_quote
The ~UNION~ operator is used to combine the resultset of two or more ~SELECT~
statements. We can use the ~UNION~ statement only if the following rules are
respected:
  + Each ~SELECT~ statement within ~UNION~ must have the same number of columns.
  + The columns must have similar data types.
  + The columns in each ~SELECT~ statement must be in the same order.

[cite:@ferrari2023postgres p.133]
#+end_quote

+ ~UNION~ is an alias to ~UNION DISTINCT~.

** ~EXCEPT~ / ~INTERSECT~

* Upsert

#+begin_quote
In PostgreSQL, the ~UPSERT~ statement does not exist as in other DBMSes. An ~UPSERT~
statement is used when we want to insert a new record on top of the existing
record or update an existing record. 
#+end_quote

The optional ~ON CONFLICT~ clause specifies an alternative action to raising a
unique violation or exclusion constraint violation error:

#+begin_src sql
  INSERT INTO table_name(c1, c2, ..., cn) VALUES(v1, v2, ..., vn)
  ON CONFLICT (...);
#+end_src

and the conflict action can be either:

+ ~DO NOTHING~.
+ ~DO UPDATE~ + (~SET~ and/or ~WHERE~)

#+begin_src sql
  INSERT INTO table_name(c1, c2, ..., cn) VALUES(v1, v2, ..., vn)
  ON CONFLICT
  DO UPDATE SET c1 = EXCLUDED.v1;
#+end_src

where ~EXCLUDED~ references the proposed new insertion row.

* ~RETURNING~

Reduces the need for an extra query as it enables you to output columns.

** Inserts
** Updates
** Deletes
