:PROPERTIES:
:ID:       de7d0e94-618f-4982-b3e5-8806d88cad5d
:END:
#+title: Erlang
#+filetags: "Functional Programming"

#+begin_quote
The Erlang view of the world can be summarized in the following statments

+ Everything is a process.
+ Processes are strongly isolated.
+ Process creation and destruction is a lightweight operation.
+ Message passing is the only way for processes to interact.
+ Processes have unique names.
+ If you know the name of a process you can send it a message.
+ Error handling is non-local.
+ Processes do what they are supposed to do or fail.

[cite:@armstrong2003 p.39]:
#+end_quote

* History

#+begin_quote
Erlang was heavily influenced by other [[id:171718cd-10fd-484b-8d77-0ffcffc29163][Functional Programming]] languages. One
functional principle is to treat functions as first-class citizens; they can be
assigned to variables, be part of complex data structures, be passed as function
arguments, or be returned as the results of function
calls. [cite:@cesarini2016designing p.25]
#+end_quote

#+begin_quote
In the mid-1980s, Ericsson's Computer Science Laboratory was given the task of
investigating programming languages suitable for programming the next generation
of telecom products. Joe Armstrong, Robert Virding, and Mike Williams - under the
supervision of Bjarne Däcker - spent two years prototyping telecom applications
with all of the available programming languages of the time. Their conclusion
was that although many of the languages had interesting and relevant features,
no single language encompassed them all. As a result, they decided to invent
their own. Erlang was influenced by functional languages such as ML and Miranda,
concurrent languages such as ADA, Modula, and Chill, as well as the Prolog logic
programming language. The software upgrade properties of Smalltalk played a
role, as did the Ericsson proprietary languages EriPascal and PLEX.

(...)

The history of Erlang is important in understanding its philosophy. Although
many languages were developed before finding their niche, Erlang was developed
to solve the “time-to-market” requirements of distributed, fault-tolerant,
massively concurrent, soft real-time systems. The fact that web services, retail
and commercial banking, computer telephony, messaging systems, and enterprise
integration, to mention but a few, happen to share the same requirements as
telecom systems explains why Erlang is gaining headway in these sectors.
[cite:@cesarini2009erlang p.3]
#+end_quote
