:PROPERTIES:
:ID:       cac62596-b63c-4d61-90d1-689f6faaa4b1
:END:
#+title: The Consolation of Philosophy (Boethius)

#+begin_quote
Anicius Manlius Severinus Boethius' Consolation of Philosophy was one of the
most widely read and influential texts in medieval Europe. (...) Boethius wrote
the Consolation circa AD 523, while in prison in Ticinum (now Pavia) awaiting
his eventual execution. (...). Boethius had a highly successful political
career, serving as senator, consul, and eventually in the powerful position of
magister officiorum for the Ostrogoth King Theodoric the Great. As we learn in
Book I of the Consolation, however, Boethius' political enemies accused him of
treason and sacrilege. As a result, Theodoric had him imprisoned and eventually
killed. Of course, Boethius was not only an influential political figure but
also a scholar. He wrote on music, mathematics, and Christian theology, and
produced commentaries on philosophical texts by Porphyry, Aristotle, and
Cicero. His life goal was to translate the complete works of both Plato and
Aristotle into Latin, accompanied by commentaries that would show how their
respective and sometimes opposed philosophical views could be harmonized.

[cite:@wiitala2024boethius p.1 chapter.1]
#+end_quote
