:PROPERTIES:
:ID:       1a477871-5172-46c1-af5e-461de148ebf0
:END:
#+title: Logic Programming

#+begin_quote
Logic programming, as well as its sister approach, [[id:171718cd-10fd-484b-8d77-0ffcffc29163][Functional Programming]],
departs radically from the mainstream of computer languages. Rather then being
derived, by a series of abstractions and reorganizations, from the von Neumann
machine model and instruction set, it is derived from an abstract model, which
has no direct relation to or dependence on to one machine model or another.

(...)

In its ultimate and purest form, logic programming suggests that even explicit
instructions for operation not be given but rather that the knowledge about the
problem and assumptions sufficient to solve it be stated explicitly, as logical
axioms.

(...)

These ideas can be summarized in the following two metaphorical
equations:

+ ~program~ = set of axioms.
+ ~computation~ = constructive proof of a goal statement from the program.

The ideas behind these equations can be traced back as far as intuitionistic
mathematics and proof theory of the early twentieth century. They are related to
Hilbert's program, to base the entire body of mathematical knowledge on logical
foundations and to provide mechanical proofs for its theories, starting from the
axioms of logic and set theory alone.

[cite:@sterling1994art p.3-4 chap.1]
#+end_quote
