:PROPERTIES:
:ID:       e96c3bdf-e6a5-405c-900b-ad7fc1404ab4
:END:
#+title: pg_stat_statements
#+filetags: :postgresql: :sql:

* Advanced statistics

#+begin_quote
While the [[id:1949c98e-e1c0-474b-b383-c76aa418d583][PostgreSQL]] statistics collector is rich and mature, having to monitor
connection activity can be a little tricky since the ~pg_stat_activity~ catalog
does not provide historical information. (...)

The ~pg_stat_statements~ extension solves this problem by providing a single view
that gives you a full history of executed statements, timing, and other little
details that can come in very handy when doing introspection. Moreover,
~pg_stat_statements~ provides a count of how many times the same statement has
been executed, resulting in important information that queries might need to pay
attention to for optimization purposes. [cite:@ferrari2023postgres p.600]
#+end_quote

Since the extension is already shipped, the only thing an administrator needs to
do is to enable it in a database cluster. You can do it by editing the
~postgresql.conf~ file and adding the following line:

#+begin_src text
  shared_preload_libraries = 'pg_stat_statements'
#+end_src

or add it like this (it requires a restart of the database cluster).

#+begin_src sql
  ALTER SYSTEM SET shared_preload_libraries = 'pg_stat_statements';
#+end_src

then verify if it works and enable the extension in your database.

#+begin_src sql
  -- Check if pg_stat_statements shows up
  SHOW shared_preload_libraries;

  -- Then enable it
  CREATE extension pg_stat_statements;
#+end_src

#+begin_src sql
  show seq_page_cost;
  show cpu_tuple_cost;
#+end_src
#+caption: This is where cost estimates are taken from.

** Usage

| Column Name      | Description                                               |
|------------------+-----------------------------------------------------------|
| ~query~            | Text of a representative statement in a parametrized form |
| ~query_id~         | Hashcode to identity identical queries                    |
| ~calls~            | Amount of times a statement has been called               |
| ~total_exec_time~  | Total execution time of all statements, in ms             |
| ~mean_exec_time~   | Mean execution time in ms                                 |
| ~total_plan_time~  | Total time spent planning the statement, in milliseconds  |
| ~mean_plan_time~   | Mean planning time, in ms                                 |
| ~shared_blks_hit~  | Blocks hit in the shared buffers                          |
| ~shared_blks_read~ | Blocks read into the shared buffers                                                        |
| ~dbid~             | Useful in environments with multiple replicas             |

*** Useful Queries

#+begin_src sql
  SELECT 
    calls, 
    mean_exec_time, 
    total_exec_time,
    100.0 * shared_blks_hit / nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent, 
    queryid, 
    regexp_replace(query, '[\n\r]+', ' ', 'g') as formatted_query 
  FROM pg_stat_statements 
  ORDER BY total_exec_time DESC 
  LIMIT 10;
#+end_src
#+caption: Sort the queries with the time spent running, with a formatted query and shared blocks hit percentage

#+begin_src sql
  SELECT
    auth.rolname,
    query,
    db.datname,
    calls,
    min_exec_time,
    max_exec_time
  FROM pg_stat_statements
  JOIN pg_authid auth ON auth.oid = userid
  JOIN pg_database db ON db.oid = dbid
  ORDER BY calls DESC;
#+end_src


