:PROPERTIES:
:ID:       43fceaac-e397-4876-90a5-4bd25f4bfebc
:END:
#+title: Promela
#+STARTUP: latexpreview
#+Html_MATHJAX: align: left indent: 5em tagside: left
#+filetags: :computer-science:formal-methods:model-checking:

#+begin_quote
While Promela can generally be seen as a fairly standard imperative programming
language, it does have some novel features. It is a non-deterministic,
multi-process, language, incorporating Dijkstra's guarded commands and Hoare's
communication channels. In particular, this communication via channels can be
defined to be synchronous (i.e. rendezvous) or asynchronous (i.e. buffered).

Crucially for many contemporary applications, Promela also allows for the
dynamic creation of concurrent processes and communication channels.

[cite:@fisher2011introduction p.144 chap.5 part.5.3.1]
#+end_quote

* Channels and Communication

#+begin_quote
Channels are unidirectional structures that exist between two processes (they
were characterized in various algebraic approaches such as [[id:a473063d-55c1-4a3b-b6df-07a532104934][CCS]] and CSP)... For
example if a channel exists between C_1 and C_2, then C_1 can send a message to C_2
down this channel:

[cite:@fisher2011introduction p.152 chap.5 part.5.3.1]
#+end_quote
