name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Cache Submodules
        id: cache-submodule
        uses: actions/cache@v4
        with:
          path: |
            org-cv
          key: ${{ runner.os }}-submodules

      - name: Checkout git submodules
        if: steps.cache-submodule.outputs.cache-hit != 'true'
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Build website
        run: |
          mkdir -p "$HOME/.emacs.d/"
          touch "$HOME/.emacs.d/.org-id-locations"
          nix develop .#ci -c just build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

